Added legalMoves for King and Rook + some tests ( will add more tests )
azizsonawalla/Chess-AI pull request #9
Opened 2021-02-22 22:15 UTC by cynzy

2021-02-22 22:54 UTC, azizsonawalla commented on src/Chess/ChessPieces.hs
> +-- Get positions preceding (and including) one with enemy piece, or preceding (but not including) one with friendly piece (whichever is earlier)
I think these additions are duplicated

2021-02-23 01:58 UTC, azizsonawalla requested changes
Comments above

2021-02-23 07:31 UTC, cynzy commented on src/Chess/ChessPieces.hs
> +-- Get positions preceding (and including) one with enemy piece, or preceding (but not including) one with friendly piece (whichever is earlier)
removed!

2021-02-23 07:31 UTC, cynzy reviewed
removed duplicate code

2021-02-24 01:36 UTC, azizsonawalla requested changes
Other than the one small change, looks good! Thanks so much!

2021-02-24 01:36 UTC, azizsonawalla commented on test/TestChessBoards.hs
> +board11_F8 = [('E', 7), ('G', 7), ('H', 6)]
```suggestion
board13_F8 = [('E', 7), ('G', 7), ('H', 6)]
```

2021-02-24 01:51 UTC, azizsonawalla approved these changes

2021-02-24 01:51 UTC, merged